import { SubjectCategory } from '../entities/subject.entity';
import { TopicDifficulty } from '../entities/topic.entity';
import { SeedCountry } from './yks-exam-pack.seed';

export const SAT_EXAM_PACK_DATA: SeedCountry = {
  code: 'US',
  name: 'United States',
  nativeName: 'United States',
  defaultTimezone: 'America/New_York',
  educationSystems: [
    {
      code: 'US_COLLEGE_BOARD',
      name: 'US Higher Education Admissions / College Board',
      nativeName: 'College Board Higher Education Assessment System',
      exams: [
        {
          code: 'SAT',
          name: 'Digital SAT',
          nativeName: 'College Board Digital Scholastic Assessment Test (SAT)',
          description: 'Official College Board Digital SAT Suite for undergraduate university admissions.',
          versions: [
            {
              version: '2026-Digital',
              displayName: 'Digital SAT Curriculum (2026-2027)',
              validFrom: '2026-08-01T00:00:00Z',
              validTo: '2027-08-31T23:59:59Z',
              officialSourceUrl: 'https://satsuite.collegeboard.org/digital',
              verifiedAt: '2026-08-20T00:00:00Z',
              verifiedBy: 'College Board Assessment Division',
              isCurrent: true,
              sections: [
                {
                  code: 'SAT_RW',
                  name: 'Reading and Writing',
                  orderIndex: 1,
                  description: 'Digital SAT Reading and Writing Section (Craft & Structure, Information & Ideas, Standard English Conventions, Expression of Ideas).',
                  subjects: [
                    {
                      code: 'SAT_RW_CRAFT_STRUCTURE',
                      name: 'Craft and Structure',
                      category: SubjectCategory.LANGUAGE_LITERATURE,
                      orderIndex: 1,
                      colorCode: '#4F46E5',
                      iconName: 'book-open-outline',
                      topics: [
                        {
                          code: 'SAT_RW_CS_WORDS_IN_CONTEXT',
                          name: 'Words in Context (Vocabulary & High-Utility Words)',
                          orderIndex: 1,
                          estimatedHours: 6,
                          importanceWeight: 5,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_RW_CS_TEXT_STRUCTURE',
                          name: 'Text Structure and Purpose (Overall Structure & Part Functions)',
                          orderIndex: 2,
                          estimatedHours: 6,
                          importanceWeight: 4,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_RW_CS_CROSS_TEXT',
                          name: 'Cross-Text Connections (Comparing Paired Passages & Perspectives)',
                          orderIndex: 3,
                          estimatedHours: 5,
                          importanceWeight: 4,
                          difficulty: TopicDifficulty.HARD,
                        },
                      ],
                    },
                    {
                      code: 'SAT_RW_INFO_IDEAS',
                      name: 'Information and Ideas',
                      category: SubjectCategory.LANGUAGE_LITERATURE,
                      orderIndex: 2,
                      colorCode: '#0284C7',
                      iconName: 'text-outline',
                      topics: [
                        {
                          code: 'SAT_RW_II_CENTRAL_IDEAS',
                          name: 'Central Ideas and Details (Key Arguments & Stated Details)',
                          orderIndex: 1,
                          estimatedHours: 5,
                          importanceWeight: 5,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_RW_II_COMMAND_EVIDENCE_TEXT',
                          name: 'Command of Evidence: Textual (Literary & Informational Quotes)',
                          orderIndex: 2,
                          estimatedHours: 6,
                          importanceWeight: 5,
                          difficulty: TopicDifficulty.HARD,
                        },
                        {
                          code: 'SAT_RW_II_COMMAND_EVIDENCE_QUANT',
                          name: 'Command of Evidence: Quantitative (Graphs, Tables, Charts)',
                          orderIndex: 3,
                          estimatedHours: 5,
                          importanceWeight: 4,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_RW_II_INFERENCES',
                          name: 'Inferences (Logical Passages Completion & Deductions)',
                          orderIndex: 4,
                          estimatedHours: 6,
                          importanceWeight: 5,
                          difficulty: TopicDifficulty.HARD,
                        },
                      ],
                    },
                    {
                      code: 'SAT_RW_CONVENTIONS',
                      name: 'Standard English Conventions',
                      category: SubjectCategory.LANGUAGE_LITERATURE,
                      orderIndex: 3,
                      colorCode: '#059669',
                      iconName: 'spellcheck',
                      topics: [
                        {
                          code: 'SAT_RW_SEC_BOUNDARIES',
                          name: 'Sentence Boundaries (Clauses, Run-ons, Comma Splices, Semicolons)',
                          orderIndex: 1,
                          estimatedHours: 5,
                          importanceWeight: 5,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_RW_SEC_FORM_STRUCTURE_SENSE',
                          name: 'Form, Structure, and Sense (Subject-Verb Agreement, Verb Tense, Pronouns, Modifiers)',
                          orderIndex: 2,
                          estimatedHours: 6,
                          importanceWeight: 5,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_RW_SEC_PUNCTUATION',
                          name: 'Punctuation & Nonessential Elements (Colons, Dashes, Apostrophes, Parentheses)',
                          orderIndex: 3,
                          estimatedHours: 4,
                          importanceWeight: 4,
                          difficulty: TopicDifficulty.EASY,
                        },
                      ],
                    },
                    {
                      code: 'SAT_RW_EXPRESSION',
                      name: 'Expression of Ideas',
                      category: SubjectCategory.LANGUAGE_LITERATURE,
                      orderIndex: 4,
                      colorCode: '#D97706',
                      iconName: 'draw-outline',
                      topics: [
                        {
                          code: 'SAT_RW_EOI_RHETORICAL_SYNTHESIS',
                          name: 'Rhetorical Synthesis (Bullet-Point Notes to Effective Draft)',
                          orderIndex: 1,
                          estimatedHours: 5,
                          importanceWeight: 4,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_RW_EOI_TRANSITIONS',
                          name: 'Transitions (Connecting Thoughts, Contrast, Cause & Effect Words)',
                          orderIndex: 2,
                          estimatedHours: 5,
                          importanceWeight: 5,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                      ],
                    },
                  ],
                },
                {
                  code: 'SAT_MATH',
                  name: 'Math',
                  orderIndex: 2,
                  description: 'Digital SAT Math Section (Algebra, Advanced Math, Problem-Solving and Data Analysis, Geometry and Trigonometry with Built-in Desmos Calculator).',
                  subjects: [
                    {
                      code: 'SAT_MATH_ALGEBRA',
                      name: 'Algebra',
                      category: SubjectCategory.MATHEMATICS,
                      orderIndex: 1,
                      colorCode: '#2563EB',
                      iconName: 'calculator-variant-outline',
                      topics: [
                        {
                          code: 'SAT_MATH_ALG_LINEAR_EQ_1VAR',
                          name: 'Linear Equations in One Variable',
                          orderIndex: 1,
                          estimatedHours: 5,
                          importanceWeight: 5,
                          difficulty: TopicDifficulty.EASY,
                        },
                        {
                          code: 'SAT_MATH_ALG_LINEAR_FUNCTIONS',
                          name: 'Linear Functions & Graphs (Slope, Intercepts, Rate of Change)',
                          orderIndex: 2,
                          estimatedHours: 6,
                          importanceWeight: 5,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_MATH_ALG_LINEAR_EQ_2VAR',
                          name: 'Linear Equations in Two Variables',
                          orderIndex: 3,
                          estimatedHours: 5,
                          importanceWeight: 4,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_MATH_ALG_SYSTEMS_LINEAR_EQ',
                          name: 'Systems of Two Linear Equations (Algebraic & Graphical Solutions)',
                          orderIndex: 4,
                          estimatedHours: 6,
                          importanceWeight: 5,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_MATH_ALG_LINEAR_INEQUALITIES',
                          name: 'Linear Inequalities in One and Two Variables',
                          orderIndex: 5,
                          estimatedHours: 4,
                          importanceWeight: 4,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                      ],
                    },
                    {
                      code: 'SAT_MATH_ADVANCED',
                      name: 'Advanced Math',
                      category: SubjectCategory.MATHEMATICS,
                      orderIndex: 2,
                      colorCode: '#7C3AED',
                      iconName: 'function-variant',
                      topics: [
                        {
                          code: 'SAT_MATH_ADV_EQUIVALENT_EXPR',
                          name: 'Equivalent Expressions (Polynomials, Factoring, Exponents & Radicals)',
                          orderIndex: 1,
                          estimatedHours: 6,
                          importanceWeight: 5,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_MATH_ADV_NONLINEAR_EQ_1VAR',
                          name: 'Nonlinear Equations in One Variable (Quadratics & Extraneous Solutions)',
                          orderIndex: 2,
                          estimatedHours: 7,
                          importanceWeight: 5,
                          difficulty: TopicDifficulty.HARD,
                        },
                        {
                          code: 'SAT_MATH_ADV_SYSTEMS_NONLINEAR_EQ',
                          name: 'Systems of Linear and Nonlinear Equations',
                          orderIndex: 3,
                          estimatedHours: 5,
                          importanceWeight: 4,
                          difficulty: TopicDifficulty.HARD,
                        },
                        {
                          code: 'SAT_MATH_ADV_NONLINEAR_FUNCTIONS',
                          name: 'Nonlinear Functions (Quadratic, Exponential, Polynomial Graphs & Vertex Forms)',
                          orderIndex: 4,
                          estimatedHours: 7,
                          importanceWeight: 5,
                          difficulty: TopicDifficulty.HARD,
                        },
                      ],
                    },
                    {
                      code: 'SAT_MATH_PROBLEM_SOLVING',
                      name: 'Problem-Solving and Data Analysis',
                      category: SubjectCategory.MATHEMATICS,
                      orderIndex: 3,
                      colorCode: '#0D9488',
                      iconName: 'chart-bell-curve-cumulative',
                      topics: [
                        {
                          code: 'SAT_MATH_PSD_RATIOS_RATES_UNITS',
                          name: 'Ratios, Rates, Proportional Relationships, and Unit Conversions',
                          orderIndex: 1,
                          estimatedHours: 5,
                          importanceWeight: 5,
                          difficulty: TopicDifficulty.EASY,
                        },
                        {
                          code: 'SAT_MATH_PSD_PERCENTAGES',
                          name: 'Percentages & Percent Change Applications',
                          orderIndex: 2,
                          estimatedHours: 4,
                          importanceWeight: 5,
                          difficulty: TopicDifficulty.EASY,
                        },
                        {
                          code: 'SAT_MATH_PSD_ONE_VAR_DATA',
                          name: 'One-Variable Data: Center, Spread, Distributions & Standard Deviation',
                          orderIndex: 3,
                          estimatedHours: 5,
                          importanceWeight: 4,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_MATH_PSD_TWO_VAR_DATA',
                          name: 'Two-Variable Data: Models, Scatterplots & Lines of Best Fit',
                          orderIndex: 4,
                          estimatedHours: 5,
                          importanceWeight: 4,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_MATH_PSD_PROBABILITY',
                          name: 'Probability and Conditional Probability (Two-Way Tables)',
                          orderIndex: 5,
                          estimatedHours: 4,
                          importanceWeight: 4,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_MATH_PSD_STAT_INFERENCE',
                          name: 'Inference from Sample Statistics and Margin of Error',
                          orderIndex: 6,
                          estimatedHours: 4,
                          importanceWeight: 3,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_MATH_PSD_EVAL_CLAIMS',
                          name: 'Evaluating Statistical Claims (Observational Studies vs Experiments)',
                          orderIndex: 7,
                          estimatedHours: 3,
                          importanceWeight: 3,
                          difficulty: TopicDifficulty.EASY,
                        },
                      ],
                    },
                    {
                      code: 'SAT_MATH_GEOMETRY_TRIG',
                      name: 'Geometry and Trigonometry',
                      category: SubjectCategory.MATHEMATICS,
                      orderIndex: 4,
                      colorCode: '#EA580C',
                      iconName: 'triangle-outline',
                      topics: [
                        {
                          code: 'SAT_MATH_GEO_AREA_VOLUME',
                          name: 'Area and Volume Formulas (Prisms, Cylinders, Cones, Spheres)',
                          orderIndex: 1,
                          estimatedHours: 4,
                          importanceWeight: 4,
                          difficulty: TopicDifficulty.EASY,
                        },
                        {
                          code: 'SAT_MATH_GEO_LINES_ANGLES_TRIANGLES',
                          name: 'Lines, Angles, and Triangles (Congruence & Similarity)',
                          orderIndex: 2,
                          estimatedHours: 5,
                          importanceWeight: 4,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_MATH_GEO_RIGHT_TRIANGLES_TRIG',
                          name: 'Right Triangles and Trigonometry (Sine, Cosine, Tangent, Radians)',
                          orderIndex: 3,
                          estimatedHours: 6,
                          importanceWeight: 5,
                          difficulty: TopicDifficulty.MEDIUM,
                        },
                        {
                          code: 'SAT_MATH_GEO_CIRCLES',
                          name: 'Circles (Arc Length, Sector Area, Circle Equation on Coordinate Plane)',
                          orderIndex: 4,
                          estimatedHours: 5,
                          importanceWeight: 4,
                          difficulty: TopicDifficulty.HARD,
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
